### ISSUE TITLE
Can not load "webpack"!

### ISSUE THREAD

**Issue by AshMarie-Miller** [sitepoint-editors/angular-todo-app#4]
Hello. I'm following your tutorial, and when I run unit tests, I get the following error: "Can not load "webpack"!"

**Comment by jvandemo** [comment]
@AshMilDevigner &mdash; Have you tried cloning this repository to see if that works for you? Thanks!

**Comment by AdamWojda** [comment]
@AshMilDevigner — I was having the same issue. You have to uninstall old CLI and get the new one like that:

```
npm uninstall angular-cli -g
npm install @angular/cli -g
```

**Comment by jvandemo** [comment]
@AdamWojda &mdash; Thank you for jumping in.

@AshMilDevigner &mdash; Can you try updating Angular CLI? Thanks again!
